"""
EPI demo - Refund approval agent.
Generated by `epi dev`. Edit freely.
"""

import os
import time

from epi_recorder import get_current_session, record, wrap_client  # noqa: F401


DEMO_WORKFLOW_NAME = "Refund approval investigation"
DEMO_TAGS = ["demo", "refund", "human-review"]
DEMO_GOAL = "Decide whether a high-value refund should be approved safely."
DEMO_NOTES = (
    "Starter case for the EPI investigation viewer. "
    "Shows a refund decision, supporting evidence, and a required human review handoff."
)
DEMO_METRICS = {
    "refund_amount_usd": 900.0,
    "manager_review_threshold_usd": 500.0,
}


class _MockMsg:
    role = "assistant"
    content = (
        "Approved. Order ORD-9001 qualifies: Gold customer, $900, "
        "12 days since purchase (within 30-day window). Risk: low."
    )


class _MockChoice:
    finish_reason = "stop"
    message = _MockMsg()


class _MockUsage:
    prompt_tokens = 38
    completion_tokens = 28
    total_tokens = 66


class _MockResponse:
    choices = [_MockChoice()]
    usage = _MockUsage()


class _MockCompletions:
    def create(self, **kwargs):
        time.sleep(0.25)
        return _MockResponse()


class _MockChat:
    completions = _MockCompletions()


class _MockClient:
    chat = _MockChat()


def run_refund_agent():
    with record(
        "demo_refund.epi",
        workflow_name=DEMO_WORKFLOW_NAME,
        tags=DEMO_TAGS,
        goal=DEMO_GOAL,
        notes=DEMO_NOTES,
        metrics=DEMO_METRICS,
        metadata_tags=DEMO_TAGS,
    ):
        session = get_current_session()

        if session:
            session.log_step(
                "agent.run.start",
                {
                    "agent_name": "RefundApprovalAgent",
                    "agent_type": "decision",
                    "user_input": "Process refund for order ORD-9001 ($900)",
                    "goal": DEMO_GOAL,
                },
            )
            session.log_step(
                "policy.check",
                {
                    "policy_name": "high_value_refund_review",
                    "rule": "Refunds above $500 require human review before payout.",
                    "result": "review_required",
                    "evidence": {
                        "order_id": "ORD-9001",
                        "amount_usd": 900,
                        "threshold_usd": 500,
                    },
                },
            )
            session.log_step(
                "tool.call",
                {
                    "tool": "lookup_order",
                    "input": {"order_id": "ORD-9001"},
                },
            )
            session.log_step(
                "tool.response",
                {
                    "tool": "lookup_order",
                    "output": {
                        "order_id": "ORD-9001",
                        "amount_usd": 900,
                        "customer_status": "gold",
                        "days_since_purchase": 12,
                        "review_threshold_usd": 500,
                    },
                    "status": "success",
                },
            )

        use_real = False
        try:
            from openai import OpenAI

            if os.getenv("OPENAI_API_KEY"):
                use_real = True
        except ImportError:
            pass

        model = "gpt-4o" if use_real else "mock-llm"
        msgs = [
            {"role": "system", "content": "You are a refund decision agent. Be concise."},
            {
                "role": "user",
                "content": "Order ORD-9001: $900, gold customer, 12 days old. Approve?",
            },
        ]

        if session:
            session.log_step(
                "llm.request",
                {"provider": "openai", "model": model, "messages": msgs},
            )

        import time as _time

        _t0 = _time.time()

        if use_real:
            print("[EPI demo] Using real OpenAI API")
            client = wrap_client(OpenAI())
            response = client.chat.completions.create(model=model, messages=msgs)
            answer = response.choices[0].message.content
        else:
            print("[EPI demo] No OPENAI_API_KEY - using built-in mock LLM")
            response = _MockClient().chat.completions.create(model=model, messages=msgs)
            answer = response.choices[0].message.content

        _latency = round(_time.time() - _t0, 3)
        print(f"[EPI demo] Decision: {answer[:80]}")

        if session:
            session.log_step(
                "llm.response",
                {
                    "provider": "openai",
                    "model": model,
                    "choices": [
                        {
                            "message": {"role": "assistant", "content": answer},
                            "finish_reason": "stop",
                        }
                    ],
                    "usage": {
                        "prompt_tokens": getattr(
                            getattr(response, "usage", None), "prompt_tokens", 38
                        ),
                        "completion_tokens": getattr(
                            getattr(response, "usage", None), "completion_tokens", 28
                        ),
                        "total_tokens": getattr(
                            getattr(response, "usage", None), "total_tokens", 66
                        ),
                    },
                    "latency_seconds": _latency,
                },
            )
            session.log_step(
                "agent.decision",
                {
                    "decision": "approve_refund",
                    "output": {
                        "order_id": "ORD-9001",
                        "amount_usd": 900,
                        "action": "APPROVE",
                    },
                    "confidence": 0.94,
                    "rationale": answer,
                    "review_required": True,
                    "review_reason": "Refund exceeds the auto-approval threshold.",
                    "severity": "medium",
                },
            )
            session.log_step(
                "review.handoff",
                {
                    "queue": "refund-managers",
                    "reason": "Human review required for refunds above $500.",
                    "requested_action": "Approve or reject the payout.",
                },
            )
            session.log_step(
                "agent.run.end",
                {
                    "agent_name": "RefundApprovalAgent",
                    "success": True,
                },
            )

        return answer


if __name__ == "__main__":
    run_refund_agent()
