name: 'EPI Record'
description: 'Automatically record and sign AI execution using EPI.'
author: 'EPI Labs'
inputs:
  command:
    description: 'The command to run and record (e.g., "pytest", "python main.py")'
    required: true
  output:
    description: 'Name of the output .epi file'
    required: false
    default: 'evidence.epi'
  install-python:
    description: 'Whether to install Python if missing'
    required: false
    default: 'false'
  upload-artifact:
    description: 'Whether to upload the .epi file as a GitHub Artifact'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      if: inputs.install-python == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install EPI Recorder
      shell: bash
      run: |
        pip install epi-recorder
        echo "✅ EPI Recorder installed."

    - name: Run and Record
      shell: bash
      env:
        EPI_COMMAND: ${{ inputs.command }}
        EPI_OUTPUT: ${{ inputs.output }}
      run: |
        echo "📹 Starting EPI Recording for: $EPI_COMMAND"
        # Run epi record wrapping the user command
        epi record --out "$EPI_OUTPUT" -- $EPI_COMMAND
        echo "✅ Recording complete: $EPI_OUTPUT"

    - name: Verify Recording
      shell: bash
      env:
        EPI_OUTPUT: ${{ inputs.output }}
      run: |
        # Quick verification check
        epi verify "$EPI_OUTPUT"

    - name: Upload Evidence
      if: inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: evidence-package
        path: ${{ inputs.output }}
