"""
epi dev — zero-friction portable repro onboarding for EPI.

Design principles:
- Real capture first. A live-recorded case is always preferred over injected demo data.
- Label honestly. "Live captured" vs "[DEMO - simulated]" — never blur the two.
- Force the proof loop. Export + verify is the product. Users must reach it.
- Pipeline visible. Every stage prints so users see EPI working, not appearing.
- No config required. Works with no API key, no internet, no setup.
"""
from __future__ import annotations

import os
import socket
import subprocess
import sys
import time
import uuid
import webbrowser
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm

from epi_core.container import EPIContainer
from epi_core import telemetry as telemetry_core

console = Console()

# ---------------------------------------------------------------------------
# Demo script — uses real EPI SDK path (wrap_client + @record)
# Mock LLM built in so no API key is needed
# ---------------------------------------------------------------------------

_DEMO_SCRIPT = '''\
"""
EPI demo — Refund approval agent.
Generated by `epi demo`.  Edit freely.
"""
import os
import time
from pathlib import Path

from epi_recorder import record, wrap_client  # noqa: F401 — wrap_client used in real-API path

# ── Mock LLM (runs with no API key) ──────────────────────────────────────
class _MockMsg:
    role = "assistant"
    content = (
        "Approved. Order ORD-9001 qualifies: Gold customer, $900, "
        "12 days since purchase (within 30-day window). Risk: low."
    )

class _MockChoice:
    finish_reason = "stop"
    message = _MockMsg()

class _MockUsage:
    prompt_tokens = 38
    completion_tokens = 28
    total_tokens = 66

class _MockResponse:
    choices = [_MockChoice()]
    usage = _MockUsage()

class _MockCompletions:
    def create(self, **kwargs):
        time.sleep(0.25)
        return _MockResponse()

class _MockChat:
    completions = _MockCompletions()

class _MockClient:
    chat = _MockChat()


DEMO_WORKFLOW_NAME = "Refund approval investigation"
DEMO_TAGS = ["demo", "refund", "human-review"]
DEMO_GOAL = "Decide whether a high-value refund should be approved safely."
DEMO_NOTES = (
    "Starter case for the EPI investigation viewer. "
    "Shows a refund decision, supporting evidence, and a required human review handoff."
)
DEMO_METRICS = {
    "refund_amount_usd": 900.0,
    "manager_review_threshold_usd": 500.0,
}


def run_refund_agent():
    # Fixed path so `epi demo` can always find the artifact
    out = Path("epi-recordings") / "demo_refund.epi"
    out.parent.mkdir(parents=True, exist_ok=True)

    with record(
        str(out),
        workflow_name=DEMO_WORKFLOW_NAME,
        tags=DEMO_TAGS,
        goal=DEMO_GOAL,
        notes=DEMO_NOTES,
        metrics=DEMO_METRICS,
        metadata_tags=DEMO_TAGS,
    ):
        from epi_recorder import get_current_session
        session = get_current_session()
        assert session is not None

        session.log("agent.run.start",
            agent_name="RefundApprovalAgent",
            agent_type="decision",
            user_input="Process refund for order ORD-9001 ($900)",
            goal=DEMO_GOAL,
        )
        session.log("policy.check",
            policy_name="high_value_refund_review",
            rule="Refunds above $500 require human review before payout.",
            result="review_required",
            evidence={"order_id": "ORD-9001", "amount_usd": 900, "threshold_usd": 500},
        )
        session.log("tool.call", tool="lookup_order", input={"order_id": "ORD-9001"})
        session.log("tool.response",
            tool="lookup_order",
            status="success",
            output={
                "order_id": "ORD-9001",
                "amount_usd": 900,
                "customer_status": "gold",
                "days_since_purchase": 12,
                "review_threshold_usd": 500,
            },
        )

        # Intentional secret in content — redacted by default before seal
        session.log("config.note",
            note="demo only",
            api_key="sk-" + ("d" * 40),
        )

        use_real = False
        try:
            from openai import OpenAI
            if os.getenv("OPENAI_API_KEY"):
                use_real = True
        except ImportError:
            pass

        model = "gpt-4o-mini" if use_real else "mock-llm"
        msgs = [
            {"role": "system", "content": "You are a refund decision agent. Be concise."},
            {"role": "user", "content": "Order ORD-9001: $900, gold customer, 12 days old. Approve?"},
        ]
        session.log("llm.request", provider="openai", model=model, messages=msgs)

        import time as _time
        _t0 = _time.time()
        if use_real:
            print("[EPI demo] Using real OpenAI API")
            client = wrap_client(OpenAI())
            response = client.chat.completions.create(model=model, messages=msgs)
            answer = response.choices[0].message.content
        else:
            print("[EPI demo] No OPENAI_API_KEY — using built-in mock LLM")
            response = _MockClient().chat.completions.create(model=model, messages=msgs)
            answer = response.choices[0].message.content
        _latency = round(_time.time() - _t0, 3)
        print(f"[EPI demo] Decision: {answer[:100]}")

        session.log("llm.response",
            provider="openai",
            model=model,
            choices=[{"message": {"role": "assistant", "content": answer}, "finish_reason": "stop"}],
            usage={
                "prompt_tokens": getattr(getattr(response, "usage", None), "prompt_tokens", 38),
                "completion_tokens": getattr(getattr(response, "usage", None), "completion_tokens", 28),
                "total_tokens": getattr(getattr(response, "usage", None), "total_tokens", 66),
            },
            latency_seconds=_latency,
        )
        session.log("agent.decision",
            decision="approve_refund",
            output={"order_id": "ORD-9001", "amount_usd": 900, "action": "APPROVE"},
            confidence=0.94,
            rationale=answer,
            review_required=True,
            review_reason="Refund exceeds the auto-approval threshold.",
            severity="medium",
        )
        session.log("review.handoff",
            queue="refund-managers",
            reason="Human review required for refunds above $500.",
            requested_action="Approve or reject the payout.",
        )
        session.log("agent.run.end", agent_name="RefundApprovalAgent", success=True)
        return answer


if __name__ == "__main__":
    run_refund_agent()
    print("\\n[EPI demo] Sealed → epi-recordings/demo_refund.epi")
'''


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_free_port(preferred: int = 8787) -> int:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", preferred))
            return preferred
    except OSError:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", 0))
            return s.getsockname()[1]


def _wait_for_port(host: str, port: int, timeout: float = 20.0) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection((host, port), timeout=0.5):
                return True
        except OSError:
            time.sleep(0.3)
    return False


def _find_demo_epi(stem: str = "demo_refund") -> Optional[Path]:
    """Find the most recently written .epi file matching stem."""
    candidates: list[Path] = []
    for search_dir in (Path("epi-recordings"), Path(".")):
        candidates.extend(search_dir.glob(f"{stem}*.epi"))
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _ingest_epi_into_gateway(epi_path: Path, storage_dir: Path) -> Optional[str]:
    """
    Read a local .epi case file and push it into the gateway case store.
    Returns the case_id on success, None on failure.
    Labels the case "[Live captured]" so it's visually distinct from seeded demo data.
    """
    try:
        from epi_gateway.worker import EvidenceWorker

        try:
            EPIContainer.detect_container_format(epi_path)
        except Exception:
            return None

        try:
            manifest_payload = EPIContainer.read_member_json(epi_path, "manifest.json")
            manifest: dict = manifest_payload if isinstance(manifest_payload, dict) else {}
        except Exception:
            manifest = {}

        steps = EPIContainer.read_steps(epi_path)

        case_id = (
            manifest.get("recording_id")
            or manifest.get("id")
            or f"live-{uuid.uuid4().hex[:8]}"
        )
        created_at = manifest.get("created_at") or datetime.now(timezone.utc).isoformat()

        worker = EvidenceWorker(storage_dir=storage_dir)
        payload = {
            "id": case_id,
            "title": "[Live captured] Refund approval investigation - ORD-9001",
            "created_at": created_at,
            "manifest": manifest,
            "steps": steps,
            "analysis": {
                "review_required": True,
                "summary": (
                    "Agent approved a $900 refund for Gold customer ORD-9001. "
                    "Human review is still required because the amount exceeds the $500 threshold. "
                    "Confidence: 94%."
                ),
            },
        }
        result = worker.upsert_case_payload(payload)
        return result.get("id") or case_id

    except Exception as exc:
        console.print(f"[yellow][!][/yellow] Could not ingest the case file: {exc}")
        return None


def _seed_simulated_case(storage_dir: Path) -> str:
    """
    Inject a clearly-labeled demo case as fallback.
    Always returns a case_id (creates a new UUID if needed).
    """
    case_id = "demo-simulated-refund-9001"
    now_iso = datetime.now(timezone.utc).isoformat()

    try:
        from epi_gateway.worker import EvidenceWorker

        worker = EvidenceWorker(storage_dir=storage_dir)
        payload = {
            "id": case_id,
            "title": "[DEMO - simulated] Refund ORD-9001 - $900 (Gold customer, 12 days)",
            "created_at": now_iso,
            "analysis": {
                "review_required": True,
                "summary": (
                    "Simulated: agent approved $900 refund. "
                    "This case was seeded by `epi dev` because the demo script did not "
                    "produce a live recording. Run `epi dev` again after fixing any errors "
                    "to get a real captured case."
                ),
            },
            "steps": [
                {
                    "kind": "agent.run.start",
                    "content": {
                        "agent_name": "RefundApprovalAgent",
                        "agent_type": "decision",
                        "user_input": "Process refund for order ORD-9001 ($900)",
                        "goal": "Determine whether to approve or reject the refund",
                        "timestamp": now_iso,
                    },
                    "seq": 1,
                    "timestamp": now_iso,
                },
                {
                    "kind": "tool.call",
                    "content": {"tool": "lookup_order", "input": {"order_id": "ORD-9001"}, "timestamp": now_iso},
                    "seq": 2,
                    "timestamp": now_iso,
                },
                {
                    "kind": "tool.response",
                    "content": {
                        "tool": "lookup_order",
                        "output": {"order_id": "ORD-9001", "amount_usd": 900, "customer_status": "gold", "days_since_purchase": 12},
                        "status": "success",
                        "timestamp": now_iso,
                    },
                    "seq": 3,
                    "timestamp": now_iso,
                },
                {
                    "kind": "llm.request",
                    "content": {
                        "provider": "openai",
                        "model": "gpt-4o",
                        "messages": [
                            {"role": "system", "content": "You are a refund decision agent."},
                            {"role": "user",   "content": "Order ORD-9001: $900, gold, 12 days. Approve?"},
                        ],
                        "timestamp": now_iso,
                    },
                    "seq": 4,
                    "timestamp": now_iso,
                },
                {
                    "kind": "llm.response",
                    "content": {
                        "provider": "openai",
                        "model": "gpt-4o",
                        "choices": [{"message": {"role": "assistant", "content": "Approved. Gold customer, within return window. Risk: low."}, "finish_reason": "stop"}],
                        "usage": {"prompt_tokens": 38, "completion_tokens": 28, "total_tokens": 66},
                        "latency_seconds": 0.25,
                        "timestamp": now_iso,
                    },
                    "seq": 5,
                    "timestamp": now_iso,
                },
                {
                    "kind": "agent.decision",
                    "content": {
                        "decision": "approve_refund",
                        "output": {"order_id": "ORD-9001", "amount_usd": 900, "action": "APPROVE"},
                        "confidence": 0.94,
                        "rationale": "Approved. Gold customer, within return window. Risk: low.",
                        "review_required": True,
                        "timestamp": now_iso,
                    },
                    "seq": 6,
                    "timestamp": now_iso,
                },
                {
                    "kind": "agent.run.end",
                    "content": {"agent_name": "RefundApprovalAgent", "success": True, "timestamp": now_iso},
                    "seq": 7,
                    "timestamp": now_iso,
                },
            ],
        }
        worker.upsert_case_payload(payload)
    except Exception as exc:
        console.print(f"[yellow][!][/yellow] Could not seed simulated case: {exc}")

    return case_id


def _run_demo_script(script_path: Path, env: dict) -> bool:
    """Run the demo script. Returns True if it exited with code 0."""
    try:
        result = subprocess.run(
            [sys.executable, str(script_path)],
            env=env,
            timeout=60,
        )
        return result.returncode == 0
    except subprocess.TimeoutExpired:
        console.print("[yellow][!][/yellow] Demo script timed out (60s)")
        return False
    except Exception as exc:
        console.print(f"[yellow][!][/yellow] Demo script error: {exc}")
        return False
def _ensure_default_key_trusted() -> None:
    """Auto-trust the default signing key so demo verify shows PASS."""
    try:
        from epi_core.keys import KeyManager
        trusted_dir = Path.home() / ".epi" / "trusted_keys"
        target = trusted_dir / "default.pub"
        if target.exists():
            return
        trusted_dir.mkdir(parents=True, exist_ok=True)
        manager = KeyManager()
        manager.trust_key("default", trusted_keys_dir=trusted_dir)
    except Exception:
        pass



def _auto_export_and_verify(storage_dir: Path, case_id: str) -> Optional[Path]:
    """
    Export the case to a .epi case file and run epi verify on it.
    Prints the full verify output so the user sees the signed proof.
    Returns the exported path or None on failure.
    """
    from epi_gateway.worker import EvidenceWorker
    from epi_gateway.main import _build_gateway_signer, _build_settings_from_env

    out_path = Path("refund_case.epi").resolve()

    console.print()
    console.print("[dim]Exporting the case file...[/dim]")

    worker = EvidenceWorker(storage_dir=storage_dir)

    try:
        settings = _build_settings_from_env()
        signer = _build_gateway_signer(settings)
    except Exception:
        signer = None

    try:
        worker.export_case(case_id, out_path, signer_function=signer)
        signed = signer is not None
        console.print(f"[green][OK][/green] Exported: {out_path}")
        if signed:
            console.print("[green][OK][/green] Signed with Ed25519 key")
            _ensure_default_key_trusted()
        else:
            console.print("[yellow][!][/yellow] Unsigned (run `epi keys generate` to enable signing)")
    except Exception as exc:
        console.print(f"[red][FAIL][/red] Export failed: {exc}")
        return None

    console.print()
    console.print("[dim]Running: epi verify refund_case.epi[/dim]")
    console.print()

    result = subprocess.run(
        [sys.executable, "-m", "epi_cli", "verify", str(out_path)],
        capture_output=False,     # let output flow to terminal
        timeout=15,
    )

    return out_path if result.returncode == 0 else None


# ---------------------------------------------------------------------------
# Command
# ---------------------------------------------------------------------------

app = typer.Typer(help="Zero-friction developer onboarding for EPI.")


def _run_fast_demo(
    *,
    demo_script: Path,
    no_run: bool,
    no_verify: bool,
    no_browser: bool,
    force_script: bool,
) -> Path | None:
    """Record → verify → view without gateway. Returns path to .epi or None."""
    console.print()
    console.print(Panel.fit(
        "[bold cyan]epi demo[/bold cyan] — record · seal · verify · view\n"
        "[dim]No API key. No server. One portable .epi file.[/dim]",
        border_style="cyan",
    ))
    console.print()

    # Always refresh generated script unless user keeps a custom path
    if force_script or not demo_script.exists() or demo_script.name == "demo_refund.py":
        # Overwrite stock demo so users always get the polished script
        if demo_script.name == "demo_refund.py" or not demo_script.exists():
            demo_script.write_text(_DEMO_SCRIPT, encoding="utf-8")
            console.print(f"  [green]✓[/green] Demo script ready     [cyan]{demo_script.name}[/cyan]")
        else:
            console.print(f"  [dim]Using existing {demo_script.name}[/dim]")
    else:
        console.print(f"  [dim]Using existing {demo_script.name}[/dim]")

    # Ensure default key exists so the artifact signs cleanly
    try:
        from epi_core.keys import KeyManager
        km = KeyManager()
        try:
            km.generate_keypair("default", overwrite=False)
        except Exception:
            pass
        _ensure_default_key_trusted()
    except Exception:
        pass

    epi_path: Optional[Path] = None
    if not no_run:
        console.print("  [dim]Recording refund agent (mock LLM if no OPENAI_API_KEY)…[/dim]")
        run_env = os.environ.copy()
        run_env.setdefault("EPI_NOTARIZE", "0")  # fast offline demo
        ok = _run_demo_script(demo_script, env=run_env)
        if not ok:
            console.print("  [yellow]![/yellow] Demo script exited non-zero — checking for artifact anyway")
        time.sleep(0.2)
        epi_path = _find_demo_epi("demo_refund")
        if epi_path is None:
            # Direct path fallback
            candidate = Path("epi-recordings") / "demo_refund.epi"
            if candidate.exists():
                epi_path = candidate
        if epi_path is None:
            console.print("  [red]✗[/red] Could not find demo_refund.epi after the run")
            return None
        size_kb = epi_path.stat().st_size // 1024 + 1
        console.print(f"  [green]✓[/green] Sealed artifact        [cyan]{epi_path}[/cyan]  ({size_kb} KB)")
    else:
        epi_path = _find_demo_epi("demo_refund") or (Path("epi-recordings") / "demo_refund.epi")
        if not epi_path.exists():
            console.print("  [red]✗[/red] --no-run set but no demo_refund.epi found")
            return None

    if not no_verify and epi_path is not None:
        console.print("  [dim]Verifying offline…[/dim]")
        result = subprocess.run(
            [sys.executable, "-m", "epi_cli", "verify", "--json", str(epi_path)],
            capture_output=True,
            text=True,
            timeout=30,
        )
        integrity = signature = "?"
        if result.returncode == 0 and result.stdout.strip():
            try:
                import json as _json
                report = _json.loads(result.stdout)
                facts = report.get("facts") or {}
                integrity = "PASS" if facts.get("integrity_ok") else "FAIL"
                signature = "PASS" if facts.get("signature_valid") else "FAIL"
            except Exception:
                integrity = signature = "OK" if result.returncode == 0 else "FAIL"
        else:
            integrity = signature = "FAIL" if result.returncode else "OK"
            if result.stderr:
                console.print(f"  [dim]{result.stderr.strip()[:200]}[/dim]")

        ok_color = "green" if integrity == "PASS" and signature == "PASS" else "yellow"
        console.print(f"  [{ok_color}]✓[/{ok_color}] Offline verify         integrity={integrity}  signature={signature}")

        # Prove redaction worked on the intentional demo secret
        try:
            steps = EPIContainer.read_steps(epi_path)
            blob = str(steps)
            if "sk-" + ("d" * 40) not in blob and "REDACTED" in blob:
                console.print("  [green]✓[/green] Secrets redacted       demo API key not present in steps")
            elif "sk-" + ("d" * 40) not in blob:
                console.print("  [green]✓[/green] Secrets redacted       no raw demo key in steps")
        except Exception:
            pass

    if not no_browser and epi_path is not None:
        console.print("  [dim]Opening viewer…[/dim]")
        view_rc = subprocess.run(
            [sys.executable, "-m", "epi_cli", "view", "--native", str(epi_path)],
            timeout=30,
        )
        if view_rc.returncode == 0:
            console.print("  [green]✓[/green] Viewer opened")
        else:
            # Fallback: extract viewer.html and open file://
            try:
                import tempfile
                import zipfile
                td = Path(tempfile.mkdtemp(prefix="epi_demo_view_"))
                with EPIContainer._payload_zip_path(epi_path) as payload:
                    with zipfile.ZipFile(payload) as zf:
                        zf.extract("viewer.html", path=td)
                uri = (td / "viewer.html").resolve().as_uri()
                webbrowser.open(uri)
                console.print(f"  [green]✓[/green] Viewer opened          {uri}")
            except Exception as exc:
                console.print(f"  [yellow]![/yellow] Could not open viewer automatically: {exc}")
                console.print(f"  [dim]Run: epi view {epi_path}[/dim]")

    try:
        telemetry_core.record_first_use()
        telemetry_core.track_event(
            "epi.demo.completed",
            {"command": "demo", "source": "cli", "success": True, "mode": "fast"},
        )
    except Exception:
        pass

    console.print()
    console.print(Panel.fit(
        f"[bold green]Done.[/bold green] Your evidence file is ready.\n\n"
        f"  [cyan]{epi_path}[/cyan]\n\n"
        f"Re-check anytime:\n"
        f"  [white]epi verify {epi_path}[/white]\n"
        f"  [white]epi view {epi_path}[/white]\n\n"
        f"[dim]Optional team inbox UI: epi demo --review[/dim]",
        title="EPI demo",
        border_style="green",
    ))
    console.print()
    return epi_path


@app.callback(invoke_without_command=True)
def dev(
    ctx: typer.Context,
    port: int = typer.Option(8787, "--port", "-p", help="Local review workspace port (only with --review)."),
    storage_dir: Path = typer.Option(Path("./evidence_vault"), "--storage-dir", help="Local case storage directory (only with --review)."),
    no_browser: bool = typer.Option(False, "--no-browser", help="Skip opening the browser."),
    demo_script: Path = typer.Option(Path("demo_refund.py"), "--demo-script", help="Path to demo script (auto-generated if missing)."),
    no_run: bool = typer.Option(False, "--no-run", help="Skip running the demo script."),
    no_verify: bool = typer.Option(False, "--no-verify", help="Skip offline verify step."),
    review: bool = typer.Option(
        False,
        "--review",
        help="Also start the local team review workspace (requires epi-recorder[gateway]).",
    ),
):
    """
    Fastest EPI loop: record a sample agent, seal a .epi, verify offline, open the viewer.

    No API key, no internet, no config required.
    Use --review for the optional gateway inbox UI.
    """
    if ctx.invoked_subcommand is not None:
        return

    demo_script = demo_script.resolve() if demo_script.is_absolute() else (Path.cwd() / demo_script)

    # ── Default: magic fast path (no gateway) ─────────────────────────────
    if not review:
        epi = _run_fast_demo(
            demo_script=demo_script,
            no_run=no_run,
            no_verify=no_verify,
            no_browser=no_browser,
            force_script=True,
        )
        if epi is None:
            raise typer.Exit(1)
        return

    # ── Optional: gateway review workspace ────────────────────────────────
    from epi_cli._shared import require_extra

    require_extra("gateway", "uvicorn", "epi demo --review")
    require_extra("gateway", "fastapi", "epi demo --review")

    storage_dir = storage_dir.resolve()

    # Run fast capture first so we always have a live .epi
    epi_path = _run_fast_demo(
        demo_script=demo_script,
        no_run=no_run,
        no_verify=no_verify,
        no_browser=True,  # gateway UI opens instead
        force_script=True,
    )

    console.print()
    console.print("[dim]Starting optional review workspace (--review)…[/dim]")

    actual_port = _find_free_port(port)
    if actual_port != port:
        console.print(f"[yellow]  [!] Port {port} busy — using {actual_port}[/yellow]")

    gateway_url = f"http://127.0.0.1:{actual_port}"
    gateway_env = os.environ.copy()
    gateway_env["EPI_GATEWAY_STORAGE_DIR"] = str(storage_dir)
    gateway_env["EPI_GATEWAY_RETENTION_MODE"] = "full_content"

    gateway_proc = subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "epi_gateway.main:app",
         "--host", "127.0.0.1", "--port", str(actual_port), "--log-level", "warning"],
        env=gateway_env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    if not _wait_for_port("127.0.0.1", actual_port, timeout=20.0):
        console.print("[red]  [FAIL] The local review workspace did not start.[/red]")
        gateway_proc.terminate()
        raise typer.Exit(1)

    console.print(f"[green]  [OK] Local review workspace ready -> {gateway_url}[/green]")

    case_id: Optional[str] = None
    case_source = "none"
    if epi_path and epi_path.exists():
        case_id = _ingest_epi_into_gateway(epi_path, storage_dir)
        if case_id:
            case_source = "live"
    if not case_id:
        case_id = _seed_simulated_case(storage_dir)
        case_source = "simulated"

    if not no_browser:
        time.sleep(0.3)
        webbrowser.open(gateway_url)
        console.print(f"[green]  [OK] Browser opened -> {gateway_url}[/green]")

    source_label = (
        "[green]Live captured[/green]" if case_source == "live"
        else "[yellow]DEMO - simulated[/yellow]"
    )
    console.print()
    console.print(f"  Case: Refund ORD-9001 ($900)  ({source_label})")
    console.print(f"  Storage: [cyan]{storage_dir}[/cyan]")
    console.print("  Press [bold]Ctrl+C[/bold] to stop the review workspace.")
    console.print()

    try:
        while True:
            if gateway_proc.poll() is not None:
                console.print("[red][!] The local review workspace exited unexpectedly.[/red]")
                break
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass
    finally:
        console.print()
        console.print("[dim]Stopping the local review workspace...[/dim]")
        try:
            gateway_proc.terminate()
            gateway_proc.wait(timeout=5.0)
        except Exception:
            gateway_proc.kill()
        console.print("[green][OK][/green] Stopped.")
