REPORT_HTML = r"""
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<title>EU AI Act Annex IV Report</title>
<style>
body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333}
h1{font-size:1.8rem}
.sub{color:#666}
table{width:100%;border-collapse:collapse;background:#fff}
th,td{padding:12px;border-bottom:1px solid #eee}
th{background:#2c3e50;color:#fff}
.score{font-size:2rem;font-weight:700;text-align:center;padding:30px}
</style>
</head>
<body>
<h1>EU AI Act Annex IV Compliance Report</h1>
<p class=sub>Generated: TIMESTAMP</p>
<div class=score>Overall: PCT%</div>
<table><thead><tr><th>Sec</th><th>Section</th><th>Status</th><th>Approved</th></tr></thead>
<tbody>ROWS</tbody>
</table>
<p class=footer>Generated by epi annex report</p>
</body>
</html>
"""