"""HTML report templates for Annex IV compliance reports."""

REPORT_HTML = """<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<title>EU AI Act Annex IV Report</title>
<style>
body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#333}
h1{font-size:1.8rem}
.sub{color:#666}
table{width:100%;border-collapse:collapse;background:#fff}
th,td{padding:12px;border-bottom:1px solid #eee}
th{background:#2c3e50;color:#fff}
.score{font-size:2rem;font-weight:700;text-align:center;padding:30px}
.signer-table{margin-top:30px}
.footer{margin-top:40px;font-size:0.8rem;color:#999}
</style>
</head>
<body>
<h1>EU AI Act Annex IV Compliance Report</h1>
<p class=sub>Generated: TIMESTAMP</p>
<div class=score>Overall: PCT%</div>
<table><thead><tr><th>Sec</th><th>Section</th><th>Status</th><th>Approved</th></tr></thead>
<tbody>ROWS</tbody></table>
SIGNERS_SECTION
<p class=footer>Generated by epi annex report | Document Hash: DOC_HASH</p>
</body>
</html>"""

REPORT_HTML_PDF = """<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8>
<title>EU AI Act Annex IV Compliance Report</title>
<style>
@page {
  size: A4;
  margin: 2.5cm 2cm 2.5cm 2cm;
  @bottom-center {
    content: "Page " counter(page) " of " counter(pages);
    font-size: 8pt;
    color: #888;
    font-family: sans-serif;
  }
  @bottom-left {
    content: "EPI vVERSION | DOC_HASH_SHORT";
    font-size: 7pt;
    color: #aaa;
    font-family: monospace;
  }
}
@page cover {
  @bottom-center { content: none; }
  @bottom-left { content: none; }
}

body{font-family: "DejaVu Sans", Arial, Helvetica, sans-serif; color: #2c3e50; font-size: 10pt; line-height: 1.5}
h1{font-size: 1.6rem; color: #1a252f; border-bottom: 3px solid #2c3e50; padding-bottom: 8px}
h2{font-size: 1.2rem; color: #2c3e50; margin-top: 24px; page-break-after: avoid}
.sub{color: #7f8c8d; font-size: 0.9rem}

.cover-page{page: cover; page-break-after: always; text-align: center; padding-top: 120px}
.cover-page h1{font-size: 2rem; border: none; margin-bottom: 10px}
.cover-page .subtitle{font-size: 1.1rem; color: #7f8c8d; margin-bottom: 40px}
.cover-page .meta{font-size: 0.9rem; color: #95a5a6; margin-top: 60px}
.cover-page .hash{font-family: monospace; font-size: 0.7rem; color: #bdc3c7; margin-top: 40px; word-break: break-all}

.score-section{text-align: center; padding: 20px; margin: 20px 0; border: 2px solid #2c3e50; border-radius: 8px}
.score-value{font-size: 3rem; font-weight: bold; color: #2c3e50}
.score-label{font-size: 0.9rem; color: #7f8c8d}

table{width: 100%; border-collapse: collapse; margin: 16px 0; page-break-inside: avoid}
th, td{padding: 8px 10px; text-align: left; border-bottom: 1px solid #dee2e6; font-size: 9pt}
th{background: #2c3e50; color: #fff; font-weight: 600}
tr:nth-child(even){background: #f8f9fa}

.status-complete{color: #27ae60; font-weight: 600}
.status-approved{color: #1e8449; font-weight: 600}
.status-draft{color: #f39c12; font-weight: 600}
.status-missing{color: #e74c3c; font-weight: 600}

.signer-table{margin-top: 24px}
.signer-table th{background: #34495e}

.policy-section{margin-top: 24px; page-break-before: always}
.policy-section h2{margin-bottom: 12px}
.severity-block{color: #e74c3c; font-weight: 600}
.severity-warn{color: #f39c12; font-weight: 600}

.scitt-section{margin-top: 24px; page-break-before: always}
.scitt-hash{font-family: monospace; font-size: 8pt; background: #f8f9fa; padding: 8px; border-radius: 4px; word-break: break-all}

.verification-table{margin-top: 24px}
.check-pass{color: #27ae60}
.check-fail{color: #e74c3c}

.disclaimer{margin-top: 40px; padding: 12px; border-top: 1px solid #dee2e6; font-size: 8pt; color: #95a5a6}
.disclaimer p{margin: 4px 0}
</style>
</head>
<body>
<div class="cover-page">
  <h1>EU AI Act<br>Annex IV Compliance Report</h1>
  <p class="subtitle">Tamper-Evident Evidence for High-Risk AI Systems</p>
  <p class="meta">
    Generated: TIMESTAMP<br>
    EPI Version: VERSION
  </p>
  <p class="hash">
    Document SHA-256: DOC_HASH
  </p>
</div>

<div class="score-section">
  <div class="score-value">PCT%</div>
  <div class="score-label">Overall Compliance Completion</div>
</div>

<h2>Section Status</h2>
<table>
  <thead><tr><th>Sec</th><th>Section</th><th>Status</th><th>Approved By</th></tr></thead>
  <tbody>ROWS</tbody>
</table>

SIGNERS_SECTION

POLICY_SECTION

SCITT_SECTION

VERIFICATION_SECTION

<div class="disclaimer">
  <p><strong>Disclaimer:</strong> This report is generated by EPI Recorder (epi-recorder vVERSION), an open-source evidence infrastructure tool. It does not constitute legal advice, a regulatory compliance guarantee, or regulator approval. The organization remains responsible for legal interpretation, policy, review, retention, governance, and regulatory submission.</p>
  <p>Generated by epi annex report | Document SHA-256: DOC_HASH</p>
</div>
</body>
</html>"""

__all__ = ["REPORT_HTML", "REPORT_HTML_PDF"]
